apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}
  namespace:  {{.Release.Namespace}}
spec:
  selector:
    app: {{.Values.applicationName}}
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80