apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: demo-worker-demo
spec:
  type: 0
  resourceID: /subscriptions/db80e051-2fd2-40fc-a263-9f62b1c2406d/resourceGroups/rg-mxtest-demo/providers/Microsoft.ManagedIdentity/userAssignedIdentities/demo-worker-demo
  clientID: de142493-60bb-45ab-90a7-1312df91dde8