trigger:
- main

pool:
  name: DevOpsLocal


steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.0.2'
- task: CmdLine@2
  displayName: "Terraform Init"
  inputs:
      script: |
        terraform init
      workingDirectory: '$(System.DefaultWorkingDirectory)/cloud-cli/demo-pipeline'