trigger: none

pool:
  name: DevOpsLocal

steps:

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Terraform-SP'
    KeyVaultName: 'kv-mxinfo-devops-infra'
    SecretsFilter: '*'
    RunAsPreJob: false
- task: CmdLine@2
  inputs:
    script: 'echo $(db-admin-user-name)'