trigger: none

pool:
  name: DevOpsLocal

steps:

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Terraform-SP'
    KeyVaultName: 'kv-mxinfo-devops-infra'
    SecretsFilter: '*'
    RunAsPreJob: false
- task: CmdLine@2
  inputs:
    script: 'echo $(db-admin-user-name) > secret.txt'

- task: CopyFiles@2
  inputs:
   Contents: secret.txt
   TargetFolder: '$(Build.ArtifactStagingDirectory)'
  
- task: PublishBuildArtifacts@1
  inputs:
   PathtoPublish: '$(Build.ArtifactStagingDirectory)'
   ArtifactName: 'drop'
   publishLocation: 'Container'
